-- Looking at the database table
SELECT
	*
FROM
	REQUESTLOGS;

-- Querying total requests in the table
SELECT
	SUM(ID) AS TOTALREQUESTS
FROM
	REQUESTLOGS;

-- Querying average response time of the API
SELECT
	ROUND(CAST(AVG(RESPONSETIME) AS NUMERIC), 2) AVGREQUESTTIME
FROM
	REQUESTLOGS;

-- Querying total failed responses
SELECT
	SUM(ID) AS TOTALFAILEDRESPONSE
FROM
	REQUESTLOGS
WHERE
	REQUESTSTATUS BETWEEN 400 AND 700;

-- Querying number of requests per type
SELECT
	REQUESTTYPE,
	COUNT(ID) REQUEST_COUNT
FROM
	REQUESTLOGS
GROUP BY
	REQUESTTYPE;

-- Querying number of requests per browser
SELECT
	USERAGENT,
	COUNT(ID) AS REQUEST_COUNT
FROM
	REQUESTLOGS
GROUP BY
	USERAGENT;

-- Querying rows with column names
SELECT
	ID,
	REQUESTID,
	REQUESTSTATUS,
	REQUESTTYPE,
	REQUESTTIME,
	CONTENTTYPE,
	IPADDRESS,
	OS,
	USERAGENT
FROM
	REQUESTLOGS;